NAME = libft.a
SRCS = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
       ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c \
       ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c \
       ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c \
       ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c \
       ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c \
       ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c  \
       ft_uitoa.c ft_ltoa.c ft_ultoa.c ft_uintlen.c ft_ulonglen.c \
       ft_printf.c ft_printf_convs.c ft_printf_convs_long.c ft_printf_utils.c \
       ft_printf_utils_long.c get_next_line.c
       
OBJS = $(SRCS:.c=.o)
CC = cc
CFLAGS = -g -Wall -Wextra -Werror

all: $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(NAME): $(OBJS)
	ar rc $@ $^

clean:
	rm -f $(OBJS) $(NAME)

re: fclean all
